// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearDownloads() {
  return window['go']['main']['App']['ClearDownloads']();
}

export function DownloadRegion(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['DownloadRegion'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetMapKey() {
  return window['go']['main']['App']['GetMapKey']();
}

export function ListBookmarks() {
  return window['go']['main']['App']['ListBookmarks']();
}

export function ProxyGetRequest(arg1) {
  return window['go']['main']['App']['ProxyGetRequest'](arg1);
}

export function ProxyPostRequest(arg1, arg2) {
  return window['go']['main']['App']['ProxyPostRequest'](arg1, arg2);
}

export function ResetConfig() {
  return window['go']['main']['App']['ResetConfig']();
}

export function SendUdpNumber(arg1, arg2) {
  return window['go']['main']['App']['SendUdpNumber'](arg1, arg2);
}

export function SetCompassOffset(arg1) {
  return window['go']['main']['App']['SetCompassOffset'](arg1);
}

export function SetGPSLocation(arg1, arg2) {
  return window['go']['main']['App']['SetGPSLocation'](arg1, arg2);
}

export function SetUTMLocation(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetUTMLocation'](arg1, arg2, arg3, arg4);
}

export function StartUdpListener(arg1) {
  return window['go']['main']['App']['StartUdpListener'](arg1);
}

export function StopUdpListener() {
  return window['go']['main']['App']['StopUdpListener']();
}
