// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearDownloads() {
  return window['go']['main']['App']['ClearDownloads']();
}

export function DownloadRegion(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['DownloadRegion'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function ListBookmarks() {
  return window['go']['main']['App']['ListBookmarks']();
}
