// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * @param {any} arg1
 * @param {any} arg2
 * @param {any} arg3
 * @param {any} arg4
 * @param {any} arg5
 * @param {any} arg6
 * @param {any} arg7
 */
export function DownloadRegion(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  // @ts-ignore
  return window['go']['main']['App']['DownloadRegion'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ListBookmarks() {
  // @ts-ignore
  return window['go']['main']['App']['ListBookmarks']();
}
